#!/bin/sh

# Copyright 2015 Red Hat Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

start() {

    # prepare /etc/exports
    rm /etc/exports
    for i in "$@"; do
        echo "$i *(rw,sync,no_root_squash,insecure,no_subtree_check,fsid=0)" >> /etc/exports
        echo "Serving $i"
    done

    mount -t nfsd nfds /proc/fs/nfsd
    mkdir -p /var/lib/nfs
    /usr/sbin/exportfs -r
    portmap
    /usr/sbin/rpc.mountd -V 4 -N 2 -N 3
    /usr/sbin/rpc.nfsd -N 2 -N 3 -V 4 -V 4.1 4

    echo "NFS started"
}

stop() {

    echo "Stopping NFS"

    /usr/sbin/rpc.nfsd 0
    /usr/sbin/exportfs -au
    /usr/sbin/exportfs -f
    kill $( pidof rpc.mountd )
    umount /proc/fs/nfsd
    echo > /etc/exports
    exit 0
}


trap stop TERM

start "$@"

# Ugly hack to do nothing and wait for SIGTERM
while true; do
    read
done
